sudo: required

services:
  - docker

env:
  global:
    - REGISTRY_USER=scrumteamravens
    - REGISTRY_PASS=$REGISTRY_PASS

before_script:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud --quiet config set project $PROJECT_NAME_PRD
  - gcloud auth configure-docker
  
script:
  - docker build --tag scrumteamravens/googleubuntujdk11 .
  - docker run scrumteamravens/googleubuntujdk11

after_script:
  - docker images
  
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  
deploy:
  provider: script
  script: docker push scrumteamravens/googleubuntujdk11
  on:
    branch: master